### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by martinp88** [rroylance/phaser-npm-webpack-typescript-starter-project#14]
Hello. I love your project!

However, I am not sure, how to debug it.

In my similar, simpler, project, I use the "Debugger for Chrome" plugin in VS Code. For this I need to have launch.json in .vscode folder configured. I then create breakpoints and use the Debug panel to start/play debugging. It opens new chrome window and when I e.g. click on something it shows me the line in VS Code and all the values etc.

Please, can you let me know, how you do it?

Thanks and again - great template!

**Comment by rroylance** [comment]
Hey. Glad you like the project :) 

I haven't had much time lately to put towards updating this, unfortunately, so I haven't gotten any further than I explained in the other debugging related issue (#11). 

Honestly, the reason break point support and all that wasn't included from the beginning is simply because I'm a fan of console logging for my debugging in my Phaser games. 

Hopefully I can get some time for this project soon and get some updates. In the meantime, if you want to figure out how to get it working for you and submit a pull request I'd be happy to merge it in :)

**Comment by martinp88** [comment]
Hello again. Thanks for your quick reply. If I had a chance and figure it out, I will create a pull request.

**Comment by Nepoxx** [comment]
Could you close this in favor of https://github.com/rroylance/phaser-npm-webpack-typescript-starter-project/issues/11 ?

**Comment by rroylance** [comment]
Closing to consolidate debugging related issues (#11)
