### ISSUE TITLE
Failed to compile after cloning repository

### ISSUE THREAD

**Issue by emik** [rroylance/phaser-npm-webpack-typescript-starter-project#38]
![image](https://user-images.githubusercontent.com/2894097/29417723-1d2b4c9c-8362-11e7-8881-4a2f9589e5d9.png)

There are a number of compile errors when running the project with npm run server:dev. Forgive me if I'm missing a step but I have tried it a couple times now. Cheers.

**Comment by SC0d3r** [comment]
Yeah this is because the new merges
this is not a hard problem just a few changes is needed i will open pull request but until then do these steps :
1 - go to **tsconfig** and change **es5** to **es6**
2 - go to **generateAssetsClass** (line : 166) replace that line with this line
`
shell.ShellString('\n        static get' + loaderTypes.spritesheet[i][0].toUpperCase() + '(): string { return require(\'assets/' + i + '.' + loaderTypes.spritesheet[i][0] +'\'); }').toEnd(assetsClassFile);
`
3 - go to **title.ts** (line : 45) and change 
`Assets.Spritesheets.SpritesheetsMetalslugMummy.getName()` to
`Assets.Spritesheets.SpritesheetsMetalslugMummy374518.getName()`

4 - do **$ npm run assets**

**Comment by kurtdekker** [comment]
Thank you, the above fix was precisely what I needed. Looking forward to PR #39 but in the meantime I am fully able to thunder ahead with my learnings... Awesome!

**Comment by rroylance** [comment]
#39 merged in, this should be all fixed now. Thanks all!
