### ISSUE TITLE
Specify Sprite Sheet with no JSON.

### ISSUE THREAD

**Issue by Majirefy** [rroylance/phaser-npm-webpack-typescript-starter-project#8]
Sometimes we need load a sprite sheet image file with no JSON like:

`this.game.load.spritesheet('uiButtons', Assets.Images.ImagesUiButtons.getPNG(), 260, 100);`

As you mentioned before, maybe we can specify these files with formatted name like rings[100,100].png, which indicates the frame size is 100*100.

Or just create a folder called sprite sheet and exclude it from auto loading, let users load manually.

**Comment by rroylance** [comment]
@Majirefy Support is in, I did what I mentioned before and made it so that any image with the extra bit of info in the filename gets treated as a spritesheet.

filename.[frameWidth, frameHeight, frameMax, margins,spacing].extension Where only frameWidth and frameHeight are required; 

For example;
rings.[100,100].png - Means that the rings spritesheet has frames of 100 width and 100 height, the entire sheet is frames, 0 margin, 0 spacing.

rings.[100, 100, 3, 2, 1].png - Means that the rings spritesheet has frames of 100 width and 100 height, there are 3 frames,  a margin of 2, and spacing between frames of px.

Thanks for the suggestion 👍
